<?php
/**
 * Import & Export LLMS Content
 *
 * @since 3.3.0
 * @since 3.35.0 Moved from frontend templates directory.
 *                  Added field.
 * @version 3.35.0
 */

defined( 'ABSPATH' ) || exit;

$courses = llms_get_importable_courses();
?>

<div class="wrap lifterlms llms-import-export">

	<h1 class="wp-heading-inline"><?php _e( 'Import Courses', 'lifterlms' ); ?></h1>
	<button class="page-title-action" role="button"><?php _e( 'Upload', 'lifterlms' ); ?></button>

	<div class="llms-widget" style="display: none;" id="llms-import-uploader">

		<form action="" enctype="multipart/form-data" method="POST">

			<table class="form-table">

				<tr>
					<th><label><?php _e( 'Import Course(s)', 'lifterlms' ); ?></label></th>
					<td>
						<input accept="application/json" class="widefat" name="llms_import" type="file">
						<p><em><?php _e( 'Upload export files generated by LifterLMS. Must be a ".json" file.', 'lifterlms' ); ?></em></p>
						<br>
						<button class="llms-button-primary small" type="submit"><?php _e( 'Import', 'lifterlms' ); ?></button>
					</td>
				</tr>

				<?php
					/**
					 * Fires after core importer(s) on the "Import screen".
					 *
					 * Allows 3rd parties to add their own importers to the table.
					 *
					 * @since 3.3.0
					 */
					do_action( 'lifterlms_importer_tr' );
				?>

			</table>

			<?php wp_nonce_field( 'llms-importer', 'llms_importer_nonce' ); ?>

		</form>

	</div>

	<form action="" method="POST">

		<?php include LLMS_PLUGIN_DIR . 'includes/admin/views/importable-courses.php'; ?>
		<?php wp_nonce_field( 'llms-cloud-importer', 'llms_cloud_importer_nonce' ); ?>

	</form>

</div>

<script>
( function() {
	document.querySelector( '.page-title-action' ).addEventListener( 'click', function() {
		var el = document.getElementById( 'llms-import-uploader' );
		el.style.display = 'none' === el.style.display ? 'block' : 'none';
	} );
} )();
</script>
