#
# This travis config file is intended to be used by LifterLMS Add-ons.
#
# Example usage in .travis.yml:
#
# import:
#  - gocodebox/lifterlms:.config/travis/add-on.yml
#

# Import main configs.
import:
  - gocodebox/lifterlms:.config/travis/main.yml

# Add-ons require the LifterLMS core.
install:
  - |
    if [ -z "$LLMS_BRANCH" ]; then
      - ./vendor/bin/llms-tests plugin lifterlms
    else
      - ./vendor/bin/llms-tests plugin https://github.com/gocodebox/lifterlms.git@${LLMS_BRANCH}
    fi

# Test against the "nightly" dev branch of the the LifterLMS core.
jobs:
  allow_failures:
  - env: LLMS_BRANCH=dev WP_VERSION=latest

  include:
  - name: "LLMS Nightly on PHP 7.4 and WP Latest"
    php: 7.4
    env:  LLMS_BRANCH=dev WP_VERSION=latest
