os: linux
dist: bionic
language: php

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - TESTS_DB_HOST=localhost
    - TESTS_DB_NAME=llms_tests
    - TESTS_DB_PASS=""
  jobs:
    - WP_VERSION=nightly
    - WP_VERSION=latest # 5.5
    - WP_VERSION="5.4"
    - WP_VERSION="5.3"
    - WP_VERSION="5.2"
    - WP_VERSION="5.1"

php:
  - nightly
  - 7.4
  - 7.3
  - 7.2

jobs:
  fast_finish: true

  allow_failures:
  - env: WP_VERSION=nightly
  - env: WP_VERSION=latest RUN_CODE_COVERAGE=1
  - php: nightly
    env: WP_VERSION=latest

  exclude:
  # These WP Versions don't work on PHP 7.4
  - php: 7.4
    env: WP_VERSION="5.2"
  - php: 7.4
    env: WP_VERSION="5.1"
  # These WP Versions don't work on PHP 8.0
  - php: nightly
    env: WP_VERSION="5.4"
  - php: nightly
    env: WP_VERSION="5.3"
  - php: nightly
    env: WP_VERSION="5.2"
  - php: nightly
    env: WP_VERSION="5.1"

  include:
  - name: "PHP Unit Test Coverage"
    php: 7.4
    env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    before_script:
      # Download CodeClimate Test Reporter
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
    script:
      - ./cc-test-reporter before-build
      - composer run-script tests-run -- --coverage-clover clover.xml
    after_script:
      - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

before_install:
  # Disable xDebug for faster builds
  - |
    if [ "1" != $RUN_CODE_COVERAGE ] && [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  # Raise PHP memory limit to 2048MB
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Install composer deps.
  - |
    if [ "nightly" != $TRAVIS_PHP_VERSION ]; then
      composer install
    else
      composer install php8
    fi

install:
  # Install Tests.
  - |
    if [ "nightly" != $TRAVIS_PHP_VERSION ]; then
      composer run tests-install
    else
      composer run tests-install-php8
    fi

script:
  # Check coding standards.
  - composer run-script check-cs-errors -- $( git diff --name-only --diff-filter=ACMR $TRAVIS_COMMIT_RANGE )
  # Run phpunit tests.
  - composer run-script tests-run

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: VzwXDPjuNCrKed9ACY7dwzyIjcnt6G1iC1LnKAOIx9fyPZ7TARLIf5bSa9M7P5w4uQHK7kpm5yFNtPHKGwaazZnCZxH8jcDMc4M8y3w6j9uNlbidOgfrCpp07lY6kpd8ViR7ANZ4V5Noz+ts8/gSA0yUib6vGP87s6RKHTyVTfNuFmHui7t6vF3S1VCXm4JmOrqmZbY9DlN+8JcyE0Ao3KOk/UDSCZICqo7cYnMci2oHGfb+2VRu49B61tASnV0r/dRu7gjEQTtqwElIJfuP0hGeAYc6bee5vFLA4EIdz2TMgr/Fm1El5eIg+1ZB4bOVEHzUlonLLGaUlqcYfKtmmYiV8BBnte1xBlEflLxYj92ethTUtTvkicVmtK50IlyL8kpb4WBwhXMEjSoKGLmdfaeNGKZ0vS/BnyDA0eWmt4EQ5ZVQL50ukhvmOAXhMB5T+K6Bg6T3yJzXIxej0MrSSNVygpeIwl5RqleXOKJJtJe3TsrsQfdqidXVrKAGSrwlwDRSMLC7JN3l99+5PEXzgb106TE0TBgrMOEClTVyH4gAjplqQ70diw9SAp0rnU518dTDj9HMvZ7KcGQgnAzKI82iB1LaWsWrMjqHtPbn/h+2vRDQNRnx8umnCmC8ezRr4l+xZ8Cb9KgrhvJW+bed3pQFmD/LerSuW6ZgHFsN/KI=
