const
	ChangelogEntry = require( './changelog-entry' ),
	createDistFile = require( './create-dist-file' ),
	determineVersionIncrement = require( './determine-version-increment' ),
	execSync = require( './exec-sync' ),
	getArchiveFilename = require( './get-archive-filename' ),
	getChangelogEntries = require( './get-changelog-entries' ),
	getChangelogForVersion = require( './get-changelog-for-version' ),
	getChangelogOptions = require( './get-changelog-options' ),
	getCurrentVersion = require( './get-current-version' ),
	getDefault = require( './get-default' ),
	getNextVersion = require( './get-next-version' ),
	getProjectSlug = require( './get-project-slug' ),
	{ getConfig, hasConfig } = require( './configs' ),
	logResult = require( './log-result' ),
	parseChangelogFile = require( './parse-changelog-file' ),
	pushDistFile = require( './push-dist-file' ),
	{ isAttributionValid, isEntryValid, isLinkValid, getChangelogValidationIssues } = require( './validate-changelog' );

module.exports = {
	ChangelogEntry,
	createDistFile,
	determineVersionIncrement,
	execSync,
	getArchiveFilename,
	getChangelogEntries,
	getChangelogForVersion,
	getChangelogOptions,
	getConfig,
	getCurrentVersion,
	getDefault,
	getNextVersion,
	getProjectSlug,
	hasConfig,
	logResult,
	isAttributionValid,
	isEntryValid,
	isLinkValid,
	getChangelogValidationIssues,
	parseChangelogFile,
	pushDistFile,
};
