const
	ChangelogEntry = require( './changelog-entry' ),
	createDistFile = require( './create-dist-file' ),
	determineVersionIncrement = require( './determine-version-increment' ),
	execSync = require( './exec-sync' ),
	getArchiveFilename = require( './get-archive-filename' ),
	getChangelogEntries = require( './get-changelog-entries' ),
	getChangelogForVersion = require( './get-changelog-for-version' ),
	getChangelogOptions = require( './get-changelog-options' ),
	getCurrentVersion = require( './get-current-version' ),
	getDefault = require( './get-default' ),
	getNextVersion = require( './get-next-version' ),
	{ isProjectPrivate, isProjectPublic, getProjectPrivacy } = require( './get-project-privacy' ),
	getProjectSlug = require( './get-project-slug' ),
	{ getConfig, hasConfig } = require( './configs' ),
	{ getFileLink, getRepoLink, getIssueLink } = require( './repo-links' ),
	logResult = require( './log-result' ),
	parseChangelogFile = require( './parse-changelog-file' ),
	parseIssueString = require( './parse-issue-string' ),
	parseMainFileMetadata = require( './pare-main-file-metadata' ), 
	pushDistFile = require( './push-dist-file' ),
	{ isAttributionValid, isEntryValid, isLinkValid, getChangelogValidationIssues } = require( './validate-changelog' );

module.exports = {
	ChangelogEntry,
	createDistFile,
	determineVersionIncrement,
	execSync,
	getArchiveFilename,
	getChangelogEntries,
	getChangelogForVersion,
	getChangelogOptions,
	getConfig,
	getCurrentVersion,
	getDefault,
	getFileLink,
	getIssueLink,
	getNextVersion,
	getProjectSlug,
	getRepoLink,
	isProjectPrivate,
	isProjectPublic,
	getProjectPrivacy,
	hasConfig,
	logResult,
	isAttributionValid,
	isEntryValid,
	isLinkValid,
	getChangelogValidationIssues,
	parseChangelogFile,
	parseIssueString,
	parseMainFileMetadata,
	pushDistFile,
};
