<?php
/**
 * Import & Export LLMS Content
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

if ( ! is_admin() ) { exit; }
?>

<div class="wrap lifterlms llms-import-export">

	<h1><?php _e( 'LifterLMS Importer', 'lifterlms' ); ?></h1>

	<div class="llms-options-page-contents llms-widget">

		<form action="" enctype="multipart/form-data" method="POST">

			<table class="form-table">

				<tr>
					<th><label><?php _e( 'Import Course(s)', 'lifterlms' ); ?></label></th>
					<td>
						<input accept="application/json" class="widefat" name="llms_import" type="file">
						<p><em><?php _e( 'Upload export files generated by LifterLMS. Must be a ".json" file.', 'lifterlms' ); ?></em></p>
						<br>
						<button class="llms-button-primary small" type="submit"><?php _e( 'Import', 'lifterlms' ); ?></button>
					</td>
				</tr>

				<?php
				/**
				 * Hook in here to add importers from other platforms, perhaps
				 */
				?>
				<?php do_action( 'lifterlms_importer_tr' ); ?>

			</table>

		</form>



	</div>

</div>
