<?php
/**
 * Locale Info
 *
 * Returns an array of associative arrays containing localization information about the specified country.
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *                                                                         *
 * Data provided by GeoNames (https://www.geonames.org/)                   *
 * under the CC4.0 License (https://creativecommons.org/licenses/by/4.0/). *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *                                                                         *
 * Note to contributors                                                    *
 *                                                                         *
 * The data contained within this file is automatically generated. Do not  *
 * modify or submit pull requests on this file directly. If you've located *
 * an issue with any of the data contained within this file please open a  *
 * new issue at https://github.com/gocodebox/lifterlms/issues/new/choose.  *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * @package LifterLMS/i18n
 *
 * @since 3.37.0 TODO
 * @version [version]
 */

defined( 'ABSPATH' ) || exit;

return array(
	'AD' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AE' => array(
		'currency' => array(
			'code' => 'AED',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AF' => array(
		'currency' => array(
			'code' => 'AFN',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'AG' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AI' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AL' => array(
		'currency' => array(
			'code' => 'ALL',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AM' => array(
		'currency' => array(
			'code' => 'AMD',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AO' => array(
		'currency' => array(
			'code' => 'AOA',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AR' => array(
		'currency' => array(
			'code' => 'ARS',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AS' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'AT' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'AU' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'authorize',
			'paypal',
			'stripe',
		),
	),
	'AW' => array(
		'currency' => array(
			'code' => 'AWG',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'AX' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'AZ' => array(
		'currency' => array(
			'code' => 'AZN',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BA' => array(
		'currency' => array(
			'code' => 'BAM',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BB' => array(
		'currency' => array(
			'code' => 'BBD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BD' => array(
		'currency' => array(
			'code' => 'BDT',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(),
	),
	'BE' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'BF' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BG' => array(
		'currency' => array(
			'code' => 'BGN',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'BH' => array(
		'currency' => array(
			'code' => 'BHD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 3,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BI' => array(
		'currency' => array(
			'code' => 'BIF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BJ' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BL' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'BM' => array(
		'currency' => array(
			'code' => 'BMD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BN' => array(
		'currency' => array(
			'code' => 'BND',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BO' => array(
		'currency' => array(
			'code' => 'BOB',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BQ' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'BR' => array(
		'currency' => array(
			'code' => 'BRL',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BS' => array(
		'currency' => array(
			'code' => 'BSD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BT' => array(
		'currency' => array(
			'code' => 'BTN',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 1,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BV' => array(
		'currency' => array(
			'code' => 'NOK',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'BW' => array(
		'currency' => array(
			'code' => 'BWP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'BZ' => array(
		'currency' => array(
			'code' => 'BZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CA' => array(
		'currency' => array(
			'code' => 'CAD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'authorize',
			'paypal',
			'stripe',
		),
	),
	'CC' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'CD' => array(
		'currency' => array(
			'code' => 'CDF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CF' => array(
		'currency' => array(
			'code' => 'XAF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'CG' => array(
		'currency' => array(
			'code' => 'XAF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CH' => array(
		'currency' => array(
			'code' => 'CHF',
			'symbol_position' => 'left',
			'thousand_separator' => '\'',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'CI' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CK' => array(
		'currency' => array(
			'code' => 'NZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CL' => array(
		'currency' => array(
			'code' => 'CLP',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CM' => array(
		'currency' => array(
			'code' => 'XAF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CN' => array(
		'currency' => array(
			'code' => 'CNY',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'CO' => array(
		'currency' => array(
			'code' => 'COP',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CR' => array(
		'currency' => array(
			'code' => 'CRC',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CU' => array(
		'currency' => array(
			'code' => 'CUP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'CV' => array(
		'currency' => array(
			'code' => 'CVE',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'CW' => array(
		'currency' => array(
			'code' => 'ANG',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'CX' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'CY' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'CZ' => array(
		'currency' => array(
			'code' => 'CZK',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'DE' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'DJ' => array(
		'currency' => array(
			'code' => 'DJF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'DK' => array(
		'currency' => array(
			'code' => 'DKK',
			'symbol_position' => 'right',
			'thousand_separator' => '',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'DM' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'DO' => array(
		'currency' => array(
			'code' => 'DOP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'DZ' => array(
		'currency' => array(
			'code' => 'DZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'EC' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'EE' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'EG' => array(
		'currency' => array(
			'code' => 'EGP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'EH' => array(
		'currency' => array(
			'code' => 'MAD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'ER' => array(
		'currency' => array(
			'code' => 'ERN',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'ES' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'ET' => array(
		'currency' => array(
			'code' => 'ETB',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'FI' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'FJ' => array(
		'currency' => array(
			'code' => 'FJD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'FK' => array(
		'currency' => array(
			'code' => 'FKP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'FM' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'FO' => array(
		'currency' => array(
			'code' => 'DKK',
			'symbol_position' => 'right',
			'thousand_separator' => '',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'FR' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'GA' => array(
		'currency' => array(
			'code' => 'XAF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GB' => array(
		'currency' => array(
			'code' => 'GBP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'authorize',
			'stripe',
		),
	),
	'GD' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GE' => array(
		'currency' => array(
			'code' => 'GEL',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GF' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GG' => array(
		'currency' => array(
			'code' => 'GBP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'GH' => array(
		'currency' => array(
			'code' => 'GHS',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'GI' => array(
		'currency' => array(
			'code' => 'GIP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GL' => array(
		'currency' => array(
			'code' => 'DKK',
			'symbol_position' => 'right',
			'thousand_separator' => '',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GM' => array(
		'currency' => array(
			'code' => 'GMD',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GN' => array(
		'currency' => array(
			'code' => 'GNF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GP' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GQ' => array(
		'currency' => array(
			'code' => 'XAF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'GR' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'GS' => array(
		'currency' => array(
			'code' => 'GBP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'GT' => array(
		'currency' => array(
			'code' => 'GTQ',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GU' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'GW' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'GY' => array(
		'currency' => array(
			'code' => 'GYD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'HK' => array(
		'currency' => array(
			'code' => 'HKD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'HM' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'HN' => array(
		'currency' => array(
			'code' => 'HNL',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'HR' => array(
		'currency' => array(
			'code' => 'HRK',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'HT' => array(
		'currency' => array(
			'code' => 'HTG',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'HU' => array(
		'currency' => array(
			'code' => 'HUF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'ID' => array(
		'currency' => array(
			'code' => 'IDR',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'IE' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'IL' => array(
		'currency' => array(
			'code' => 'ILS',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'IM' => array(
		'currency' => array(
			'code' => 'GBP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'IN' => array(
		'currency' => array(
			'code' => 'INR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'IO' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'IQ' => array(
		'currency' => array(
			'code' => 'IQD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'IR' => array(
		'currency' => array(
			'code' => 'IRR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '/',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'IS' => array(
		'currency' => array(
			'code' => 'ISK',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'IT' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'JE' => array(
		'currency' => array(
			'code' => 'GBP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'JM' => array(
		'currency' => array(
			'code' => 'JMD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'JO' => array(
		'currency' => array(
			'code' => 'JOD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 3,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'JP' => array(
		'currency' => array(
			'code' => 'JPY',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'KE' => array(
		'currency' => array(
			'code' => 'KES',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KG' => array(
		'currency' => array(
			'code' => 'KGS',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => '-',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KH' => array(
		'currency' => array(
			'code' => 'KHR',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KI' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KM' => array(
		'currency' => array(
			'code' => 'KMF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KN' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KP' => array(
		'currency' => array(
			'code' => 'KPW',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(),
	),
	'KR' => array(
		'currency' => array(
			'code' => 'KRW',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KW' => array(
		'currency' => array(
			'code' => 'KWD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 3,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KY' => array(
		'currency' => array(
			'code' => 'KYD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'KZ' => array(
		'currency' => array(
			'code' => 'KZT',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => '-',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'LA' => array(
		'currency' => array(
			'code' => 'LAK',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'LB' => array(
		'currency' => array(
			'code' => 'LBP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'LC' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'LI' => array(
		'currency' => array(
			'code' => 'CHF',
			'symbol_position' => 'left',
			'thousand_separator' => '\'',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'LK' => array(
		'currency' => array(
			'code' => 'LKR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'LR' => array(
		'currency' => array(
			'code' => 'LRD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'LS' => array(
		'currency' => array(
			'code' => 'LSL',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'LT' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'LU' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'LV' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'LY' => array(
		'currency' => array(
			'code' => 'LYD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 3,
		),
		'platforms' => array(),
	),
	'MA' => array(
		'currency' => array(
			'code' => 'MAD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MC' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MD' => array(
		'currency' => array(
			'code' => 'MDL',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'ME' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MF' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'MG' => array(
		'currency' => array(
			'code' => 'MGA',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MH' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MK' => array(
		'currency' => array(
			'code' => 'MKD',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'ML' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MM' => array(
		'currency' => array(
			'code' => 'MMK',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'MN' => array(
		'currency' => array(
			'code' => 'MNT',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MO' => array(
		'currency' => array(
			'code' => 'MOP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'MP' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'MQ' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MS' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MT' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'MU' => array(
		'currency' => array(
			'code' => 'MUR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MV' => array(
		'currency' => array(
			'code' => 'MVR',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 1,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MW' => array(
		'currency' => array(
			'code' => 'MWK',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MX' => array(
		'currency' => array(
			'code' => 'MXN',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'MY' => array(
		'currency' => array(
			'code' => 'MYR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'MZ' => array(
		'currency' => array(
			'code' => 'MZN',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NA' => array(
		'currency' => array(
			'code' => 'NAD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NC' => array(
		'currency' => array(
			'code' => 'XPF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NE' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NF' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NG' => array(
		'currency' => array(
			'code' => 'NGN',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NI' => array(
		'currency' => array(
			'code' => 'NIO',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NL' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'NO' => array(
		'currency' => array(
			'code' => 'NOK',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'NP' => array(
		'currency' => array(
			'code' => 'NPR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NR' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NU' => array(
		'currency' => array(
			'code' => 'NZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'NZ' => array(
		'currency' => array(
			'code' => 'NZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'OM' => array(
		'currency' => array(
			'code' => 'OMR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 3,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PA' => array(
		'currency' => array(
			'code' => 'PAB',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PE' => array(
		'currency' => array(
			'code' => 'PEN',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PF' => array(
		'currency' => array(
			'code' => 'XPF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PG' => array(
		'currency' => array(
			'code' => 'PGK',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PH' => array(
		'currency' => array(
			'code' => 'PHP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PK' => array(
		'currency' => array(
			'code' => 'PKR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'PL' => array(
		'currency' => array(
			'code' => 'PLN',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'PM' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PN' => array(
		'currency' => array(
			'code' => 'NZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PR' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'PS' => array(
		'currency' => array(
			'code' => 'ILS',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'PT' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'PW' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'PY' => array(
		'currency' => array(
			'code' => 'PYG',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'QA' => array(
		'currency' => array(
			'code' => 'QAR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'RE' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'RO' => array(
		'currency' => array(
			'code' => 'RON',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'RS' => array(
		'currency' => array(
			'code' => 'RSD',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'RU' => array(
		'currency' => array(
			'code' => 'RUB',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'RW' => array(
		'currency' => array(
			'code' => 'RWF',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SA' => array(
		'currency' => array(
			'code' => 'SAR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SB' => array(
		'currency' => array(
			'code' => 'SBD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SC' => array(
		'currency' => array(
			'code' => 'SCR',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SD' => array(
		'currency' => array(
			'code' => 'SDG',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'SE' => array(
		'currency' => array(
			'code' => 'SEK',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'SG' => array(
		'currency' => array(
			'code' => 'SGD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'SH' => array(
		'currency' => array(
			'code' => 'SHP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SI' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'SJ' => array(
		'currency' => array(
			'code' => 'NOK',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SK' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
			'stripe',
		),
	),
	'SL' => array(
		'currency' => array(
			'code' => 'SLL',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SM' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SN' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SO' => array(
		'currency' => array(
			'code' => 'SOS',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SR' => array(
		'currency' => array(
			'code' => 'SRD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SV' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'SX' => array(
		'currency' => array(
			'code' => 'ANG',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'SY' => array(
		'currency' => array(
			'code' => 'SYP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'SZ' => array(
		'currency' => array(
			'code' => 'SZL',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TC' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TD' => array(
		'currency' => array(
			'code' => 'XAF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TF' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'TG' => array(
		'currency' => array(
			'code' => 'XOF',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TH' => array(
		'currency' => array(
			'code' => 'THB',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TJ' => array(
		'currency' => array(
			'code' => 'TJS',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ';',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TK' => array(
		'currency' => array(
			'code' => 'NZD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'TL' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'TM' => array(
		'currency' => array(
			'code' => 'TMT',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TN' => array(
		'currency' => array(
			'code' => 'TND',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 3,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TO' => array(
		'currency' => array(
			'code' => 'TOP',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TR' => array(
		'currency' => array(
			'code' => 'TRY',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'TT' => array(
		'currency' => array(
			'code' => 'TTD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TV' => array(
		'currency' => array(
			'code' => 'AUD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TW' => array(
		'currency' => array(
			'code' => 'TWD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'TZ' => array(
		'currency' => array(
			'code' => 'TZS',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'UA' => array(
		'currency' => array(
			'code' => 'UAH',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'UG' => array(
		'currency' => array(
			'code' => 'UGX',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'UM' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'US' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'authorize',
			'paypal',
			'stripe',
		),
	),
	'UY' => array(
		'currency' => array(
			'code' => 'UYU',
			'symbol_position' => 'left',
			'thousand_separator' => '.',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'UZ' => array(
		'currency' => array(
			'code' => 'UZS',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'VA' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'VC' => array(
		'currency' => array(
			'code' => 'XCD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'VG' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'VI' => array(
		'currency' => array(
			'code' => 'USD',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'VN' => array(
		'currency' => array(
			'code' => 'VND',
			'symbol_position' => 'right',
			'thousand_separator' => '.',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'VU' => array(
		'currency' => array(
			'code' => 'VUV',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 0,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'WF' => array(
		'currency' => array(
			'code' => 'XPF',
			'symbol_position' => 'right',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'WS' => array(
		'currency' => array(
			'code' => 'WST',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'XK' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(),
	),
	'YE' => array(
		'currency' => array(
			'code' => 'YER',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'YT' => array(
		'currency' => array(
			'code' => 'EUR',
			'symbol_position' => 'right',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'ZA' => array(
		'currency' => array(
			'code' => 'ZAR',
			'symbol_position' => 'left',
			'thousand_separator' => ' ',
			'decimal_separator' => ',',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
	'ZM' => array(
		'currency' => array(
			'code' => 'ZMW',
			'symbol_position' => 'left',
			'thousand_separator' => ',',
			'decimal_separator' => '.',
			'decimals' => 2,
		),
		'platforms' => array(
			'paypal',
		),
	),
);
