(()=>{"use strict";const e={n:t=>{const s=t&&t.__esModule?()=>t.default:()=>t;return e.d(s,{a:s}),s},d:(t,s)=>{if(Array.isArray(s))for(var r=0;r<s.length;){var l=s[r++],o=s[r++];e.o(t,l)?0===o&&r++:0===o?Object.defineProperty(t,l,{enumerable:!0,value:s[r++]}):Object.defineProperty(t,l,{enumerable:!0,get:o})}else for(var l in s)e.o(s,l)&&!e.o(t,l)&&Object.defineProperty(t,l,{enumerable:!0,get:s[l]})},o:(e,t)=>Object.hasOwn(e,t)},t=window.wp.blocks,s=window.wp.components,r=window.wp.blockEditor,l=window.wp.i18n,o=window.wp.serverSideRender;var i=e.n(o);const n=window.wp.element,c=JSON.parse('{"$schema":"https://schemas.wp.org/trunk/block.json","apiVersion":2,"name":"llms/course-syllabus","title":"Course Syllabus","category":"llms-blocks","description":"Display the Course Syllabus for a specific course.","textdomain":"lifterlms","attributes":{"course_id":{"type":"integer"},"llms_visibility":{"type":"string"},"llms_visibility_in":{"type":"string"},"llms_visibility_posts":{"type":"string"}},"supports":{"align":["wide","full"]},"editorScript":"file:./index.js"}'),a=window.wp.primitives,u=window.ReactJSXRuntime,p=window.wp.data,d=window.wp.apiFetch;var m=e.n(d);const b=window.wp.htmlEntities,h=["course","lesson","llms_quiz"],w=(e,t="name")=>{const s=e?.replace("llms_",""),r=s.charAt(0).toUpperCase()+s.slice(1);return"name"===t?s:r},y=({attributes:e,setAttributes:t,postType:r="course",attribute:o="course_id",postTypeAttribute:i=null})=>{const c=Array.isArray(r)?r:[r],a=c.join(","),d=c.length>1,y=(0,p.useSelect)(e=>e("core/editor")?.getCurrentPostType(),[]),[f,g]=(0,n.useState)([]),[_,v]=(0,n.useState)(!1),[j,S]=(0,n.useState)(""),x=(0,n.useRef)(null),P=c.map(e=>w(e)).join(", "),k=c.map(e=>w(e,"title")).join(" / "),C={label:h.includes(y)?(0,l.sprintf)(
// Translators: %s = Post type name.
// Translators: %s = Post type name.
(0,l.__)("Inherit from current %s","lifterlms"),w(y)):(0,l.sprintf)(
// Translators: %s = Post type name(s).
// Translators: %s = Post type name(s).
(0,l.__)("Select %s","lifterlms"),P),value:"0"},T=(e,t)=>{const s=d?" ("+w(t,"title")+", ID: "+e.id+")":" (ID: "+e.id+")";return{label:(0,b.decodeEntities)(e.title.rendered)+s,value:e.id.toString(),postType:t}},A=e?.[o];(0,n.useEffect)(()=>{const t=setTimeout(()=>((t,s=0)=>{v(!0),x.current&&x.current.abort();const r="undefined"!=typeof AbortController?new AbortController:null;x.current=r,Promise.all(c.map(e=>m()({path:`/wp/v2/${e}?per_page=10&search=${encodeURIComponent(t)}`,signal:r?.signal}).then(t=>t.map(t=>T(t,e))))).then(t=>{const r=t.flat();if(g(r),s&&!r.some(e=>e.value===s.toString())){const t=i&&e?.[i]||c[0];m()({path:`/wp/v2/${t}?include=${s}`}).then(e=>{g([...r,...e.map(e=>T(e,t))])}).catch(()=>{})}}).catch(e=>{"AbortError"!==e?.name&&g([])}).finally(()=>{x.current===r&&v(!1)})})(j,A),300);return()=>clearTimeout(t)},[j,A,a]);const E=(0,l.sprintf)(
// Translators: %s = Post type name(s).
// Translators: %s = Post type name(s).
(0,l.__)("Select the %s to associate with this block.","lifterlms"),P);return(0,u.jsx)(s.PanelRow,{children:(0,u.jsx)(s.ComboboxControl,{label:k,help:E,value:String(A??0),options:[C,...f],onChange:e=>{const s=f.find(t=>t.value===e),r={[o]:parseInt(e,10)||0};i&&s?.postType&&(r[i]=s.postType),t(r)},onFilterValueChange:S,isLoading:_,allowReset:!1})})};(0,t.registerBlockType)(c,{icon:()=>(0,u.jsx)(a.SVG,{className:"llms-block-icon",xmlns:"http://www.w3.org/2000/svg",viewBox:"0 0 512 512",children:(0,u.jsx)(a.Path,{d:"M152.1 38.2c9.9 8.9 10.7 24 1.8 33.9l-72 80c-4.4 4.9-10.6 7.8-17.2 7.9s-12.9-2.4-17.6-7L7 113C-2.3 103.6-2.3 88.4 7 79s24.6-9.4 33.9 0l22.1 22.1 55.1-61.2c8.9-9.9 24-10.7 33.9-1.8zm0 160c9.9 8.9 10.7 24 1.8 33.9l-72 80c-4.4 4.9-10.6 7.8-17.2 7.9s-12.9-2.4-17.6-7L7 273c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l22.1 22.1 55.1-61.2c8.9-9.9 24-10.7 33.9-1.8zM224 96c0-17.7 14.3-32 32-32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-17.7 0-32-14.3-32-32zm0 160c0-17.7 14.3-32 32-32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-17.7 0-32-14.3-32-32zM160 416c0-17.7 14.3-32 32-32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32H192c-17.7 0-32-14.3-32-32zM48 368a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"})}),edit:e=>{const{attributes:t,setAttributes:o}=e,a=(0,r.useBlockProps)(),d=(()=>{const e=(0,p.useSelect)(e=>e("core/editor")?.getCurrentPostType(),[]);return h.includes(e)})(),m=((e="course")=>{const{posts:t,currentPostType:s}=(0,p.useSelect)(t=>({posts:t("core").getEntityRecords("postType",e),currentPostType:t("core/editor")?.getCurrentPostType()}),[]),r=[];return h.includes(s)||r.push({label:(0,l.__)("Select course","lifterlms"),value:0}),t?.length&&t.forEach(e=>{r.push({label:(0,b.decodeEntities)(e.title.rendered)+" (ID: "+e.id+")",value:e.id})}),h.includes(s)&&r.unshift({label:(0,l.sprintf)(
// Translators: %s = Post type name.
// Translators: %s = Post type name.
(0,l.__)("Inherit from current %s","lifterlms"),w(s)),value:0}),r?.length||r.push({label:(0,l.__)("Loading","lifterlms"),value:0}),r})(),f=(0,n.useMemo)(()=>(0,u.jsx)(i(),{block:c.name,attributes:{course_id:t.course_id??m?.[0]?.value},LoadingResponsePlaceholder:()=>(0,u.jsx)(s.Spinner,{}),ErrorResponsePlaceholder:()=>(0,u.jsx)("p",{className:"llms-block-error",children:(0,l.__)("Error loading content. Please check block settings are valid. This block will not be displayed.","lifterlms")}),EmptyResponsePlaceholder:()=>(0,u.jsx)("p",{className:"llms-block-empty",children:(0,l.__)("No syllabus found for this course. This block will not be displayed.","lifterlms")})}),[t]);return t.course_id||d||o({course_id:m?.[0]?.value}),(0,u.jsxs)(u.Fragment,{children:[(0,u.jsx)(r.InspectorControls,{children:(0,u.jsx)(s.PanelBody,{title:(0,l.__)("Course Syllabus Settings","lifterlms"),children:(0,u.jsx)(y,{attributes:t,setAttributes:o})})}),(0,u.jsx)("div",{...a,children:(0,u.jsx)(s.Disabled,{children:f})})]})}})})();