(()=>{"use strict";const e={n:t=>{const s=t&&t.__esModule?()=>t.default:()=>t;return e.d(s,{a:s}),s},d:(t,s)=>{if(Array.isArray(s))for(var l=0;l<s.length;){var r=s[l++],i=s[l++];e.o(t,r)?0===i&&l++:0===i?Object.defineProperty(t,r,{enumerable:!0,value:s[l++]}):Object.defineProperty(t,r,{enumerable:!0,get:i})}else for(var r in s)e.o(s,r)&&!e.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:s[r]})},o:(e,t)=>Object.hasOwn(e,t)},t=window.wp.blocks,s=window.wp.components,l=window.wp.blockEditor,r=window.wp.i18n,i=window.wp.serverSideRender;var o=e.n(i);const n=window.wp.element,a=JSON.parse('{"$schema":"https://schemas.wp.org/trunk/block.json","apiVersion":2,"name":"llms/course-author","title":"Course Author","category":"llms-blocks","description":"Display the Course Author’s name, avatar, and (optionally) biography for a specific course.","textdomain":"lifterlms","attributes":{"avatar_size":{"type":"integer","default":48},"bio":{"type":"string","default":"yes"},"course_id":{"type":"integer"},"llms_visibility":{"type":"string"},"llms_visibility_in":{"type":"string"},"llms_visibility_posts":{"type":"string"}},"supports":{"align":["wide","full"]},"editorScript":"file:./index.js"}'),c=window.wp.primitives,u=window.ReactJSXRuntime,p=window.wp.data,d=window.wp.apiFetch;var h=e.n(d);const m=window.wp.htmlEntities,b=["course","lesson","llms_quiz"],f=(e,t="name")=>{const s=e?.replace("llms_",""),l=s.charAt(0).toUpperCase()+s.slice(1);return"name"===t?s:l},w=({attributes:e,setAttributes:t,postType:l="course",attribute:i="course_id",postTypeAttribute:o=null})=>{const a=Array.isArray(l)?l:[l],c=a.join(","),d=a.length>1,w=(0,p.useSelect)(e=>e("core/editor")?.getCurrentPostType(),[]),[_,y]=(0,n.useState)([]),[g,v]=(0,n.useState)(!1),[j,x]=(0,n.useState)(""),C=(0,n.useRef)(null),k=a.map(e=>f(e)).join(", "),A=a.map(e=>f(e,"title")).join(" / "),P={label:b.includes(w)?(0,r.sprintf)(
// Translators: %s = Post type name.
// Translators: %s = Post type name.
(0,r.__)("Inherit from current %s","lifterlms"),f(w)):(0,r.sprintf)(
// Translators: %s = Post type name(s).
// Translators: %s = Post type name(s).
(0,r.__)("Select %s","lifterlms"),k),value:"0"},S=(e,t)=>{const s=d?" ("+f(t,"title")+", ID: "+e.id+")":" (ID: "+e.id+")";return{label:(0,m.decodeEntities)(e.title.rendered)+s,value:e.id.toString(),postType:t}},T=e?.[i];(0,n.useEffect)(()=>{const t=setTimeout(()=>((t,s=0)=>{v(!0),C.current&&C.current.abort();const l="undefined"!=typeof AbortController?new AbortController:null;C.current=l,Promise.all(a.map(e=>h()({path:`/wp/v2/${e}?per_page=10&search=${encodeURIComponent(t)}`,signal:l?.signal}).then(t=>t.map(t=>S(t,e))))).then(t=>{const l=t.flat();if(y(l),s&&!l.some(e=>e.value===s.toString())){const t=o&&e?.[o]||a[0];h()({path:`/wp/v2/${t}?include=${s}`}).then(e=>{y([...l,...e.map(e=>S(e,t))])}).catch(()=>{})}}).catch(e=>{"AbortError"!==e?.name&&y([])}).finally(()=>{C.current===l&&v(!1)})})(j,T),300);return()=>clearTimeout(t)},[j,T,c]);const R=(0,r.sprintf)(
// Translators: %s = Post type name(s).
// Translators: %s = Post type name(s).
(0,r.__)("Select the %s to associate with this block.","lifterlms"),k);return(0,u.jsx)(s.PanelRow,{children:(0,u.jsx)(s.ComboboxControl,{label:A,help:R,value:String(T??0),options:[P,..._],onChange:e=>{const s=_.find(t=>t.value===e),l={[i]:parseInt(e,10)||0};o&&s?.postType&&(l[o]=s.postType),t(l)},onFilterValueChange:x,isLoading:g,allowReset:!1})})};(0,t.registerBlockType)(a,{icon:()=>(0,u.jsx)(c.SVG,{className:"llms-block-icon",xmlns:"http://www.w3.org/2000/svg",viewBox:"0 0 448 512",children:(0,u.jsx)(c.Path,{d:"M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"})}),edit:e=>{const{attributes:t,setAttributes:i}=e,c=(0,l.useBlockProps)(),d=((e="course")=>{const{posts:t,currentPostType:s}=(0,p.useSelect)(t=>({posts:t("core").getEntityRecords("postType",e),currentPostType:t("core/editor")?.getCurrentPostType()}),[]),l=[];return b.includes(s)||l.push({label:(0,r.__)("Select course","lifterlms"),value:0}),t?.length&&t.forEach(e=>{l.push({label:(0,m.decodeEntities)(e.title.rendered)+" (ID: "+e.id+")",value:e.id})}),b.includes(s)&&l.unshift({label:(0,r.sprintf)(
// Translators: %s = Post type name.
// Translators: %s = Post type name.
(0,r.__)("Inherit from current %s","lifterlms"),f(s)),value:0}),l?.length||l.push({label:(0,r.__)("Loading","lifterlms"),value:0}),l})(),h=(0,n.useMemo)(()=>{let e=(0,r.__)("Author not found. This block will not be displayed.","lifterlms");return!t.course_id&&d.length>0&&(e=(0,r.__)("No course selected. Please choose a Course from the block sidebar panel.","lifterlms")),(0,u.jsx)(o(),{block:a.name,attributes:t,LoadingResponsePlaceholder:()=>(0,u.jsx)(s.Spinner,{}),ErrorResponsePlaceholder:()=>(0,u.jsx)("p",{className:"llms-block-error",children:(0,r.__)("Error loading content. Please check block settings are valid. This block will not be displayed.","lifterlms")}),EmptyResponsePlaceholder:()=>(0,u.jsx)("p",{className:"llms-block-empty",children:e})})},[t]);return(0,u.jsxs)(u.Fragment,{children:[(0,u.jsx)(l.InspectorControls,{children:(0,u.jsxs)(s.PanelBody,{title:(0,r.__)("Course Author Settings","lifterlms"),children:[(0,u.jsx)(s.PanelRow,{children:(0,u.jsx)(s.RangeControl,{label:(0,r.__)("Avatar Size","lifterlms"),help:(0,r.__)("The size of the avatar in pixels.","lifterlms"),value:t.avatar_size,onChange:e=>i({avatar_size:parseInt(e)}),min:0,max:300,allowReset:!0,resetFallbackValue:a.attributes.avatar_size.default,default:a.attributes.avatar_size.default})}),(0,u.jsx)(s.PanelRow,{children:(0,u.jsx)(s.ToggleControl,{label:(0,r.__)("Display Bio","lifterlms"),help:t?.bio?(0,r.__)("Author bio is displayed.","lifterlms"):(0,r.__)("Author bio is hidden.","lifterlms"),checked:"yes"===t.bio,onChange:e=>i({bio:e?"yes":"no"})})}),(0,u.jsx)(w,{...e})]})}),(0,u.jsx)("div",{...c,children:(0,u.jsx)(s.Disabled,{children:h})})]})}})})();