(()=>{"use strict";const e={n:t=>{const s=t&&t.__esModule?()=>t.default:()=>t;return e.d(s,{a:s}),s},d:(t,s)=>{if(Array.isArray(s))for(var r=0;r<s.length;){var l=s[r++],o=s[r++];e.o(t,l)?0===o&&r++:0===o?Object.defineProperty(t,l,{enumerable:!0,value:s[r++]}):Object.defineProperty(t,l,{enumerable:!0,get:o})}else for(var l in s)e.o(s,l)&&!e.o(t,l)&&Object.defineProperty(t,l,{enumerable:!0,get:s[l]})},o:(e,t)=>Object.hasOwn(e,t)},t=window.wp.blocks,s=window.wp.components,r=window.wp.blockEditor,l=window.wp.i18n,o=window.wp.serverSideRender;var n=e.n(o);const i=window.wp.element,c=JSON.parse('{"$schema":"https://schemas.wp.org/trunk/block.json","apiVersion":2,"name":"llms/course-continue","title":"Course Progress with Continue Button","category":"llms-blocks","description":"Display a progress bar with continue button for a specific course. Renders only for enrolled students.","textdomain":"lifterlms","attributes":{"course_id":{"type":"integer"},"llms_visibility":{"type":"string"},"llms_visibility_in":{"type":"string"},"llms_visibility_posts":{"type":"string"}},"supports":{"align":["wide","full"]},"editorScript":"file:./index.js"}'),a=window.wp.primitives,p=window.ReactJSXRuntime,u=window.wp.data,d=window.wp.apiFetch;var m=e.n(d);const h=window.wp.htmlEntities,w=["course","lesson","llms_quiz"],b=(e,t="name")=>{const s=e?.replace("llms_",""),r=s.charAt(0).toUpperCase()+s.slice(1);return"name"===t?s:r},f=({attributes:e,setAttributes:t,postType:r="course",attribute:o="course_id",postTypeAttribute:n=null})=>{const c=Array.isArray(r)?r:[r],a=c.join(","),d=c.length>1,f=(0,u.useSelect)(e=>e("core/editor")?.getCurrentPostType(),[]),[g,y]=(0,i.useState)([]),[_,v]=(0,i.useState)(!1),[j,x]=(0,i.useState)(""),P=(0,i.useRef)(null),S=c.map(e=>b(e)).join(", "),k=c.map(e=>b(e,"title")).join(" / "),C={label:w.includes(f)?(0,l.sprintf)(
// Translators: %s = Post type name.
// Translators: %s = Post type name.
(0,l.__)("Inherit from current %s","lifterlms"),b(f)):(0,l.sprintf)(
// Translators: %s = Post type name(s).
// Translators: %s = Post type name(s).
(0,l.__)("Select %s","lifterlms"),S),value:"0"},T=(e,t)=>{const s=d?" ("+b(t,"title")+", ID: "+e.id+")":" (ID: "+e.id+")";return{label:(0,h.decodeEntities)(e.title.rendered)+s,value:e.id.toString(),postType:t}},R=e?.[o];(0,i.useEffect)(()=>{const t=setTimeout(()=>((t,s=0)=>{v(!0),P.current&&P.current.abort();const r="undefined"!=typeof AbortController?new AbortController:null;P.current=r,Promise.all(c.map(e=>m()({path:`/wp/v2/${e}?per_page=10&search=${encodeURIComponent(t)}`,signal:r?.signal}).then(t=>t.map(t=>T(t,e))))).then(t=>{const r=t.flat();if(y(r),s&&!r.some(e=>e.value===s.toString())){const t=n&&e?.[n]||c[0];m()({path:`/wp/v2/${t}?include=${s}`}).then(e=>{y([...r,...e.map(e=>T(e,t))])}).catch(()=>{})}}).catch(e=>{"AbortError"!==e?.name&&y([])}).finally(()=>{P.current===r&&v(!1)})})(j,R),300);return()=>clearTimeout(t)},[j,R,a]);const E=(0,l.sprintf)(
// Translators: %s = Post type name(s).
// Translators: %s = Post type name(s).
(0,l.__)("Select the %s to associate with this block.","lifterlms"),S);return(0,p.jsx)(s.PanelRow,{children:(0,p.jsx)(s.ComboboxControl,{label:k,help:E,value:String(R??0),options:[C,...g],onChange:e=>{const s=g.find(t=>t.value===e),r={[o]:parseInt(e,10)||0};n&&s?.postType&&(r[n]=s.postType),t(r)},onFilterValueChange:x,isLoading:_,allowReset:!1})})};(0,t.registerBlockType)(c,{icon:()=>(0,p.jsx)(a.SVG,{className:"llms-block-icon",xmlns:"http://www.w3.org/2000/svg",viewBox:"0 0 512 512",children:(0,p.jsx)(a.Path,{d:"M448 160H320V128H448v32zM48 64C21.5 64 0 85.5 0 112v64c0 26.5 21.5 48 48 48H464c26.5 0 48-21.5 48-48V112c0-26.5-21.5-48-48-48H48zM448 352v32H192V352H448zM48 288c-26.5 0-48 21.5-48 48v64c0 26.5 21.5 48 48 48H464c26.5 0 48-21.5 48-48V336c0-26.5-21.5-48-48-48H48z"})}),edit:e=>{const{attributes:t}=e,o=(0,r.useBlockProps)(),a=((e="course")=>{const{posts:t,currentPostType:s}=(0,u.useSelect)(t=>({posts:t("core").getEntityRecords("postType",e),currentPostType:t("core/editor")?.getCurrentPostType()}),[]),r=[];return w.includes(s)||r.push({label:(0,l.__)("Select course","lifterlms"),value:0}),t?.length&&t.forEach(e=>{r.push({label:(0,h.decodeEntities)(e.title.rendered)+" (ID: "+e.id+")",value:e.id})}),w.includes(s)&&r.unshift({label:(0,l.sprintf)(
// Translators: %s = Post type name.
// Translators: %s = Post type name.
(0,l.__)("Inherit from current %s","lifterlms"),b(s)),value:0}),r?.length||r.push({label:(0,l.__)("Loading","lifterlms"),value:0}),r})(),d=(0,i.useMemo)(()=>{let e=(0,l.__)("No progress data found for this course. This block will not be displayed.","lifterlms");return!t.course_id&&a.length>0&&(e=(0,l.__)("No course selected. Please choose a Course from the block sidebar panel.","lifterlms")),(0,p.jsx)(n(),{block:c.name,attributes:t,LoadingResponsePlaceholder:()=>(0,p.jsx)(s.Spinner,{}),ErrorResponsePlaceholder:()=>(0,p.jsx)("p",{className:"llms-block-error",children:(0,l.__)("Error loading content. Please check block settings are valid. This block will not be displayed.","lifterlms")}),EmptyResponsePlaceholder:()=>(0,p.jsx)("p",{className:"llms-block-empty",children:e})})},[t]);return(0,p.jsxs)(p.Fragment,{children:[(0,p.jsx)(r.InspectorControls,{children:(0,p.jsx)(s.PanelBody,{title:(0,l.__)("Course Continue Settings","lifterlms"),children:(0,p.jsx)(f,{...e})})}),(0,p.jsx)("div",{...o,children:(0,p.jsx)(s.Disabled,{children:d})})]})}})})();