const gulp = require( 'gulp' ),
	{ unlinkSync } = require( 'fs' ),
	filesToRemove = [
		'assets/css/dancing-script-rtl.css',
		'assets/css/imperial-script-rtl.css',
		'assets/css/pirata-one-rtl.css',
		'assets/css/unifraktur-maguntia-rtl.css',
	];

/**
 * A hacky clean script that deletes RTL css files generated by the legacy styles-rtl tasks.
 *
 * The deleted files are webfont definition files which we don't need RTL stylesheets for.
 */
gulp.task( 'hacky-clean', function( cb ) {

	filesToRemove.forEach( file => {
		unlinkSync( file );
	} );

	return cb();
} );
